canonical/charmlibs

- docs/.sphinx/_static/project_specific.css
- docs/conf.py
- src/charmlibs/pathops/__init__.py
- src/charmlibs/pathops/_container_path.py
- src/charmlibs/pathops/_errors.py
- src/charmlibs/pathops/_functions.py
- src/charmlibs/pathops/_local_path.py
- src/charmlibs/pathops/_types.py
- tests/integration/pebble/test_container_path.py
- tests/unit/test_container_path.py
Add docstrings to public methods and classes and generate reference documentation. Users are expected to use the `PathProtocol` type annotations when writing substrate agnostic code -- this means they'll be seeing the `PathProtocol` docstrings in their editors a fair bit. `ContainerPath` docstrings are also likely to be surfaced in editors, and probably especially when debugging -- same for `LocalPath` but it mostly just inherits from `pathlib.PosixPath` so there's docstrings there.
Make some docs configuration changes to support this.
See the reference docs build [here](https://canonical-pathops--7.com.readthedocs.build/reference/pathops/).
There's one runtime change, where documenting a method revealed that one error case hadn't been handled, so this PR also fixes that.
The PR is …
> docs: flesh out documentation

- .github/packages.py
- .github/workflows/tests.yaml
- justfile
- pathops/tests/integration/pebble/conftest.py
- pyproject.toml
This PR replaces the current `tox.ini`, which is hardcoded to run the tests for the `pathops` package, with a `justfile` that can be parametrized by package name.
The `justfile` provides two public variables, `python` for setting the Python version, and `package` for specifying which package to run tests for. The monorepo's top-level `pyproject.toml` is updated to specify the development dependencies, allowing `uv run` to install these for linting and tests. To install the package itself for testing and static analysis, an optional dependency group is specified for each package, instructing `uv` to install the package from the local files.
The github `tests` workflow is updated to invoke `just` instead of `tox`, passing the appropriate arguments. It also features a new job which checks …
> ci: update task runners and workflows to handle the monorepo structure dynamically

- .github/packages.py
The packages script in CI previously incorrectly checked if the entire change was a directory, rather than the base of the change being a directory.
> ci: correctly detect packages if changes aren't global

- pathops/src/charmlibs/pathops/_functions.py
- pathops/src/charmlibs/pathops/_types.py
Writing charms for #16 revealed that `ensure_contents` is badly typed -- it accepts `str | os.PathLike[str] | ContainerPath`, which is fine at runtime because `LocalPath` is `os.PathLike[str]`, but means that values typed as `PathProtocol` are not acceptable arguments for `ensure_contents`. This PR fixes this by changing the accepted type to `str | os.PathLike[str] | PathProtocol`, using  private `TypeIs` function internally to handle the types.
This PR also completely drops the recommendation from the docs to use `str | os.PathLike[str] | ContainerPath`.
Resolves #15
> fix: make ensure_contents accept PathProtocol typed paths

- .github/workflows/publish-charmlibs-package.yaml
- .github/workflows/test-publish-charmlibs-package.yaml
- _charmlibs/README.md
- _charmlibs/pyproject.toml
- _charmlibs/src/charmlibs/__init__.py
This PR adds the `charmlibs` package to this repository. This is supposed to be a minimal package that just claims the name on PyPI. It shouldn't be installed, so it emits a warning at import time.
This PR also adds the workflows to publish the package to PyPI and test PyPI. Due to the monorepo structure, PyPI publication is triggered by tags being pushed, while publication to test PyPI is triggered manually.
> feat: add charmlibs package and publication actions

- .github/workflows/publish-charmlibs-package.yaml
- .github/workflows/test-publish-charmlibs-package.yaml
This PR adds the erroneously omitted 'checkout' step to the charmlibs publication workflows.
> ci: add missing checkout step to charmlibs publish workflows

- _docs/conf.py
- _docs/how-to/index.md
- _docs/how-to/python-package.md
- _docs/how-to/python-packages.md
- _docs/index.md
This PR adds a how-to guide for distributing charm libraries as Python packages. I'd greatly appreciate feedback on errors, gaps, and anything that would be better to cut completely or trim down. Docs build [here](https://canonical-charmlibs--36.com.readthedocs.build/).
> docs: add Python packages how-to

- justfile
- pathops/src/charmlibs/pathops/_container_path.py
- pathops/src/charmlibs/pathops/_local_path.py
- pathops/src/charmlibs/pathops/_types.py
- pathops/tests/integration/juju/charms/kubernetes/charmcraft.yaml
- pathops/tests/integration/juju/charms/kubernetes/src/charm.py
- pathops/tests/integration/juju/charms/kubernetes/src/common.py
- pathops/tests/integration/juju/charms/machine/charmcraft.yaml
- pathops/tests/integration/juju/charms/machine/src/charm.py
- pathops/tests/integration/juju/charms/machine/src/common.py
- pathops/tests/integration/juju/test_pathops.py
- pathops/tests/unit/test_local_path.py
This PR aligns the behaviour of the file creation methods (`mkdir`, `write_bytes`, `write_text`) when the user argument is provided but the group argument is not.
In this case, Pebble sets the group based on the user (like `chown $user: $path`), while `shutil.chown` by default does not (like `chown $user $path`). Since changing the Pebble behaviour to match `shutil` here would require additional API calls (and possibly creating the directory twice?), and since the `user` and `group` arguments for the file creation methods are an API design that follows Pebble rather than `pathlib`, `LocalPath` is updated to follow Pebble's behaviour here.
This PR updates the unit tests to reflect this change, and adds a collection of integration tests for file ownership.
Documentation of the error case …
> feat: LocalPath also sets group (if not specified) based on user

- pathops/src/charmlibs/pathops/_container_path.py
The idea that these values might be `None` in the `FileInfo` originates from the `FileInfo.Sys` [call](https://github.com/canonical/pebble/blob/bd065c759e33f2d28583228f8f57ec535bf58d1c/internals/daemon/api_files.go#L256) in Pebble's code. However, it looks like this won't ever actually fail on the Linux implementation of this interface, so we don't need to pass this on to our users here.
> fix: Fileinfo.{user,group} are typed optional but should always be there

- pathops/src/charmlibs/pathops/_container_path.py
- pathops/src/charmlibs/pathops/_errors.py
- pathops/src/charmlibs/pathops/_fileinfo.py
- pathops/src/charmlibs/pathops/_local_path.py
- pathops/src/charmlibs/pathops/_types.py
- pathops/tests/integration/pebble/test_local_path.py
- pathops/tests/unit/test_container_path.py
The current behaviour of both `ContainerPath` and `LocalPath` for `write_{bytes,text}` is to always set the mode -- even setting the default mode if none is provided. I think overriding any existing file permissions with the default when none is provided is a mistake, as (e.g.) `pathlib.Path.write_bytes(data)` doesn't change any existing file permissions. This PR modifies these methods so that the permissions are only changed if the `mode` argument is not `None`.
Tests have been expanded to cover the case of writing when the target file already exists, and updated to reflect this new behaviour.
Resolves #46
> fix: write methods no longer change existing mode unless it's passed explicitly

- pathops/src/charmlibs/pathops/_container_path.py
- pathops/src/charmlibs/pathops/_local_path.py
- pathops/src/charmlibs/pathops/_types.py
- pathops/tests/integration/juju/charms/kubernetes/charmcraft.yaml
- pathops/tests/integration/juju/charms/kubernetes/src/charm.py
- pathops/tests/integration/juju/charms/kubernetes/src/common.py
- pathops/tests/integration/juju/charms/machine/charmcraft.yaml
- pathops/tests/integration/juju/charms/machine/src/charm.py
- pathops/tests/integration/juju/charms/machine/src/common.py
- pathops/tests/integration/juju/test_pathops.py
- pathops/tests/unit/test_container_path.py
This PR makes the behaviour of the `user` and `group` args to the file creation methods consistent.
- If the file already exists, `ContainerPath.write_{bytes,text}` will no longer modify the `user` or `group` if they're not supplied explicitly, just like how we recently updated these methods to not change the `mode` if it's not supplied explicitly in #47 
- If the directory already exists, `LocalPath.mkdir` will no longer modify the `user` or `group`, even if they're passed explicitly, matching the current `ContainerPath.mkdir` behaviour, and matching the behaviour of `mode` for `mkdir`.
This PR also adds Juju integration tests to cover the `user` and `group` behaviour when the target file or directory already exists, and updates the unit tests to work with the new behaviour.
Resolves #49
> fix: consistent behaviour for mkdir chown args when exists

- _charmlibs/README.md
- _charmlibs/pyproject.toml
- _charmlibs/src/charmlibs/__init__.py
This PR expands the charmlibs package readme with additional information. This readme appears both [in the repo](https://github.com/canonical/charmtech-charmlibs/tree/main/_charmlibs) and [on PyPI](https://pypi.org/project/charmlibs/).
This PR also bumps the charmlibs package version and development status in preparation for release.
> docs: expand the charmlibs package readme

- .github/get-packages.py
This PR is a quick fix for #54 to correctly handle how `github.base_ref` evaluates outside pull requests. Specifically, when it is not set, `get-packages.py` is called with no positional argument at all.
> ci: correctly make git_base_ref an optional argument

- .github/workflows/ci.yaml
This PR is a quick fix for #54 to cleanly skip the test step if no packages are collected. Currently these are skipped with an error due to the matrix being empty, while this will have them properly be marked as skipped.
> ci: skip the tests step cleanly if no packages are collected

- .github/workflows/docs.yaml
- _docs/.readthedocs.yaml
- _docs/Makefile
- docs.just
- justfile
This PR refactors the docs CI to use `uv` to run the `sphinx` commands, and use the same command to build the docs in readthedocs as is used locally.
I've also taken the opportunity to move the commands to a `justfile` for cleaner syntax and the ability to run the docs build commands from anywhere in the repository. They're all in a separate module, `docs.just`, keeping things clean and separate. This allows the default docs build (`html`, used in readthedocs) to be run with `just docs`, while other commands can be run with (e.g.) `just docs linkcheck`.
The main `_docs/Makefile` targets are preserved for compatibility with the Canonical docs workflows, and to allow contributors who are used to this format to easily find and run the docs commands. These targets run `just`, making the …
> docs: simplify docs makefile and use just for docs

- _docs/how-to/index.md
I just noticed that the title of the how-to category should be "How-to guides" rather than "How To".
> docs: change title of how-to category

- _charmlibs/README.md
- _docs/conf.py
Now that Ops and Charmcraft docs have moved to documentation.ubuntu.com, we should update links (not time-critical, as there are redirects).
> docs: update links to Ops and Charmcraft docs

- .github/workflows/publish.yaml
This PR updates the `publish.yaml` workflow to gracefully skip the `tests` and `build-n-publish` jobs if there are no packages for publication.
> ci: skip tests and publication if no packages have had version bumps

- justfile
This respects the local pyproject.toml's pyright settings.
> ci: run static checks from inside the package directory

- .github/unify-publish-inputs.py
This will allow .devX versions to be merged into main and test released to test.pypi.org easily.
> ci: exclude dev versions from automatic publishing

- .github/workflows/ci.yaml
- .github/workflows/tests.yaml
This PR adds a static `tests-passed` job to the `ci` workflow to check if the dynamically generated jobs from the tests matrix passed (or were skipped). This is necessary because the branch protection rules require a known job ID to be specified when setting required checks (which block merging PRs). Not only do we dynamically run different jobs depending on what tests a package has (etc), but we may skip running them altogether if a package hasn't been changed in that PR.
> ci: add a static job to check if tests matrix passed/skipped

- .docs/.sphinx/requirements.txt
- .docs/extensions/package_docs.py
- docs.just
This PR changes the `just docs html` recipe to incrementally build the package reference docs, by running `sphinx-build` once for each package, with that package installed in the virtual environment. The local `package_docs` extension has been updated accordingly to only create the automodule rst file for the specified package, rather than for all packages at once. Together, this completely eliminates the need for package dependencies to be added to the docs `requirements.txt` or to `autodoc_mock_imports`.
As a developer convenience, `just docs html` can be invoked with specific package names to limit reference docs generation to only the specified packages.
The `just docs run` and `just docs linkcheck` recipes have not been modified. The `package_docs` extension will skip generating the …
> docs: try building package reference docs individually

- .github/CODEOWNERS
This PR switches ownership of everything currently specified in the `CODEOWNERS` file from `charm-tech` to `charmlibs-maintainers`. The `charmlibs-maintainers` team is currently the exact same people, but the code review settings are different: only I will be requested for reviews, so the rest of the team should not get spammed. However, the rest of the team still has code owner permissions, and can provide the required approvals to merge PRs affecting the files the team owns.
> ci: switch from charm-tech to charmlibs-maintainers

- justfile
As an alternative to #138, flip the order of the command we run in `just format` to `ruff format` *then* `ruff check --fix`, as this is what charmers have found works best -- thanks @PietroPasotti.
> ci: check then format is wrong, we should format then check

- .github/get-functional-test-matrix.py
The script that parse `tool.charmlibs.functional` doesn't handle an empty `ubuntu` list correctly -- this should be equivalent to not specifying `ubuntu` at all, otherwise (if the package has `tests/functional`), the functional tests job will run with an empty `ubuntu` list for the matrix, and fail.
> ci: correctly handle empty ubuntu version config for functional tests

- justfile
- test-requirements.txt
In a previous PR I suggested that we didn't need `just add`, because `uv add --constraints` didn't respect the constraints for the package being added -- that is, if `pytest` is in our constraints with some version, `uv add --constraints=$FILE pytest` will still install the latest version of `pytest`. But it does seem important to provide a way for library authors to add their own dependencies while respecting our test package versions (this became clear while writing the tutorial in #159).
This PR achieves this by moving the test dependencies to a `requirements.txt` format file suitable for use with both `uv run --with-requirements` and `uv add --constraints`, which also feels like a more idiomatic way to specify dependency versions. `uv run` invocations are updated accordingly. …
> ci: add just add command (again)

- .example/pyproject.toml
- .template/{{ cookiecutter.project_slug }}/pyproject.toml
This PR adds the `tool.ruff.extend-per-file-ignores` table to the template and example's `pyproject.toml`.
> docs: show ruff extend-per-file-ignores table in template pyproject.toml

- snap/src/charmlibs/snap/_snap.py
- snap/tests/unit/test_snap.py
`snap.ensure` requires `revision` to be `int | None`, while `snap.add` and `snap.Snap.ensure` require it to be `str | None`. We consistently use `str` internally (with `''` as the default value rather than `None`). This PR allows the three public methods to accept `str | int | None` for better consistency with each other -- it's a backwards compatible change because it only widens the accepted type.
There's now a small behaviour change if the integer `0` is used for `snap.add` or `snap.Snap.ensure` -- previously this would be a type checking error, but would be converted to `''` internally at runtime. Now it will become the string `'0'`. This seems more correct than converting it to `''`. I couldn't find any charms using `revision=0`.
> feat: consistently allow revision to be int or str in public methods

- pyproject.toml
This PR updates the repo-level `pyproject.toml` to use `ruff`s `exclude` field instead of `extend-exclude`, so that packages that `extend` this config can use `extend-exclude` freely. Because the `exclude` field completely overrides any default exclusions, we add [ruff's defaults](https://docs.astral.sh/ruff/configuration/) here explicitly.
> ci: use exclude instead of extend-exclude in base pyproject.toml

- .docs/explanation/charmlibs-publishing.md
This PR adds sections and a little bit of connective tissue to the publishing explanation.
> docs: add sections to the publishing explanation

- CODEOWNERS
This PR adds an explicit entry to the `CODEOWNERS` file for `charmlibs-snap`.
> ci: add explicit codeowners for charmlibs-snap

- pyproject.toml
This PR updates the glob for the `tests` directories in the global `ruff` config for `per-file-ignores` to use `**` instead of `*`, including `interfaces/foo/tests` and `interfaces/foo/interface/tests`.
> chore: apply global test per-file-ignores to interfaces

- .scripts/ls.py
This PR updates `.scripts/ls.py` to use `tomllib` for two purposes:
1. Only count a directory as a package if the `pyproject.toml` file has a `project` table -- this will allow us to use `pyproject.toml` files for tool configuration in non-package directories (like interface directories that only have the interface definition).
2. Remove the `aliases` table and read the package's distribution name from the `pyproject.toml` file directly.
> ci: allow pyproject.toml in non package dirs

- interfaces/tls_certificates/src/charmlibs/interfaces/tls_certificates/_version.py
This PR bumps the version of the `charmlibs-interfaces-tls_certificates` lib to `1.0.0` to trigger a release.
The release for this library was tested by releasing the `1.0.0.dev0` version to: https://test.pypi.org/project/charmlibs-interfaces-tls-certificates/
> feat: release charmlibs-interfaces-tls_certificates 1.0.0

- .scripts/ls.py
This PR corrects a bug with how we were calling `tomllib.load` -- the file must be opened in binary mode.
> ci: open toml file in binary mode when using tomllib.load

- justfile
This PR updates the `just static` recipe, used for type checking locally and in CI, to install `pytest-interface-tester` when running `pyright`. This is to support type checking the `schema.py` and `test_provider.py` and `test_requirer.py` files added in interface definitions (e.g.: #174).
I'm not sure if this is the right approach.
- One alternative would be to require interface libraries to add `pytest-interface-tester` to their `lint` dependency group -- but how would we handle interfaces without a library?
- Another idea would be to support some dependency configuration for the interfaces themselves, e.g. a `requirements.txt` file under `interfaces/<interface name>/interface` alongside the `vN` directories. This would require some logic to handle the file not existing, since it won't …
> ci: install pytest-interface-tester when type checking
